Contenedor/App1/urls.py
from django.urls import path
from .views import IndexView, AutorView

urlpatterns = [
    path('', IndexView),
    path('autor/<int:id>', AutorView)
]

Contenedor/Taller/urls.py
from django.contrib import admin
from django.urls import path, include
from App1.views import IndexView

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("App1.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Contenedor/App1/models.py
from django.db import models

# Create your models here.
class Profesion(models.Model):
    nombre = models.CharField(max_length=75, verbose_name="Nombre")
    
    def __str__(self):
        return self.nombre

class AutorDb(models.Model):
    nombre = models.CharField(max_length=75, verbose_name="Nombre")
    fecha_nacimiento = models.DateField(verbose_name="Fecha Nacimiento", null=False, blank=False)
    fecha_fallecimiento = models.DateField(verbose_name="Fecha Fallecimiento", null=True, blank=True)
    profesion = models.ManyToManyField(Profesion, verbose_name="Profesion")
    nacionalidad = models.CharField(max_length=50, verbose_name="Nacionalidad")
    
    class Meta:
        db_table = "Autores"
        verbose_name = "Autor"
        verbose_name_plural = "Autores"
    
    def __str__(self) -> str:
        return self.nombre


class FraseDb(models.Model):
    cita = models.TextField(max_length=400, verbose_name="Cita")
    autor_fk = models.ForeignKey(AutorDb, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = "Frase"
        verbose_name_plural = "Frases"

Contenedor/App1/views.py
from django.shortcuts import render, get_object_or_404
from .models import AutorDb, FraseDb
# from django.http import HttpResponse

# Create your views here.
def IndexView(request):
    '''Esto es la página principal'''
    
    objeto = AutorDb.objects.filter(nombre="Hola").order_by("-id")
    
    return render(request, "index.html", {"objeto":objeto})

def AutorView(request, id):
    autor = get_object_or_404(AutorDb, id=id)
    return render(request, "autor.html", {"objeto":autor})

Contenedor/App1/templates/autor.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Prueba</title>
  </head>
  <body>
    <h1>{{objeto.nombre}}</h1>
    
    <ul>
      {%for i in objeto.frasedb_set.all %}

      <li>{{i.cita}}</li>

      {% endfor %}
    </ul>
  </body>
</html>

Contenedor/App1/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Taller</title>
    <link rel="stylesheet" href="{% static "estilos.css" %}">
</head>
<body>
    <h1>Hola Comunidad</h1>
    <br>
    <p>Hola como estan, espero que esten bien.</p>

    <hr>

    <ul>
        {%for i in objeto %}

        <li>
            <a href="autor/{{i.id}}">
                {{i.nombre}}
            </a>
        </li>
        <ul>
            {%for u in i.profesion.all %}
            <li>{{u}}</li>
            {% endfor %}
        </ul>

        {% endfor %}

        {% if objeto %}
        <h2>TENEMOS EL OBJETO</h2>
        {% else %}
        <h2>NO TENEMOS EL OBJETO</h2>
        {% endif %}
    </ul>

    <script src="{% static "script.js" %}"></script>
</body>
</html>